Moodle-Migration-WebUI/Controllers/CommandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Moodle_Migration_WebUI.Hubs;
using Moodle_Migration_WebUI.Interfaces;
using Moodle_Migration_WebUI.Services;
using System.Threading.Tasks;

namespace Moodle_Migration_WebUI.Controllers
{
    public class CommandController : Controller
    {
        private readonly ICommandService _commandService;
        private readonly IHubContext<StatusHub> _hubContext;

        public CommandController(ICommandService commandService, IHubContext<StatusHub> hubContext)
        
        {
            _commandService = commandService;
            _hubContext = hubContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Execute(string command)
        {
            string currentUser = User.Identity?.Name;
            await _hubContext.Clients.User(currentUser).SendAsync("ReceiveStatus", "Starting...");
            // Simulate processing
            await Task.Delay(1000);
            await _hubContext.Clients.User(currentUser).SendAsync("ReceiveStatus", "Processing...");

            var result = await _commandService.ExecuteCommand(command);
            ViewBag.Result = result;
            await Task.Delay(2000);
            await _hubContext.Clients.User(currentUser).SendAsync("ReceiveStatus", "Completed.");
            await Task.Delay(2000);
            return View("Index");
        }
    }
}


Moodle-Migration-WebUI/Views/Shared/_HelpPartial.cshtml
<div class="help-section">
    <h3>Available actions:</h3>
    <ul>
        <li><strong>-h, --help</strong> - Show help information</li>
        <li><strong>-h, --help {option}</strong> - Show help information for specific option</li>
        <ul>
            <li><strong>-u, --user</strong></li>
            <li><strong>-c, --course</strong></li>
            <li><strong>-ct, --category</strong></li>
        </ul>
        <li><strong>-u, --user {operation} {parameters}</strong> - Perform user operation (details or create) with specified parameters</li>
        <li><strong>-c, --course {operation} {parameters}</strong> - Perform course operation (detail) with specified parameters</li>
        <li><strong>-ct, --category {operation} {parameters}</strong> - Perform course operation (create) with specified parameters</li>
        <ul>
            <li><strong>Available operations</strong></li>
            <li><strong>-d, --display</strong></li>
            <li><strong>-c, --create</strong></li>
        </ul>
    </ul>
    <hr />
    <div class="user-help">
        <h4>User actions</h4>
        <ul>
            <li><strong>-u -d</strong> - Display all users without filtering</li>
            <li><strong>-u -d {property1}={value1} {property2}={value2}</strong> - Display users filtering by properties</li>
            <li><strong>-u -c {parameter}={value}</strong> - Import Users and/or Cohorts from elfh to Moodle</li>
            <ul>
                <li><strong>id={int}</strong> - Import user based on elfh UserId</li>
                <li><strong>username={string}</strong> - Import user based on elfh UserName</li>
                <li><strong>ugid={int}</strong> - Import user group as Cohort with option to import all users</li>
            </ul>
        </ul>
    </div>
    <hr />
    <div class="course-help">
        <h4>Course actions</h4>
        <ul>
            <li><strong>-c -d</strong> - Display all courses without filtering</li>
            <li><strong>-c -d {field}={value}</strong> - Display courses filtering by specific field</li>
            <ul>
                <li><strong>id={int}</strong> - Course id</li>
                <li><strong>ids={int,int,int}</strong> - Comma separated course ids</li>
                <li><strong>shortname={string}</strong> - Course short name</li>
                <li><strong>category={int}</strong> - Category id the course belongs to</li>
                <li><strong>sectionid={int}</strong> - Section id that belongs to a course</li>
            </ul>
        </ul>
    </div>
    <hr />
    <div class="category-help">
        <h4>Category actions</h4>
        <ul>
            <li><strong>-ct -d</strong> - Display all categories without filtering</li>
            <li><strong>-ct -d {property1}={value1} {property2}={value2}</strong> - Display categories filtering by properties</li>
            <li><strong>-ct -c id={value}</strong> - Creates a top-level category with the option to create child components</li>
            <ul>
                <li><strong>id={int}</strong> - Elfh programme component id</li>
            </ul>
        </ul>
    </div>
</div>

Moodle-Migration-WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Moodle Migration WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Moodle_Migration_WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Command" asp-action="Index">Moodle Migration from elfh Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity?.IsAuthenticated ?? false)
                {
                    <div class="d-flex align-items-center">
                        <div class="nhsuk-account__login nhsuk-header__not-mobile ms-3 d-flex align-items-center">                        
                            <a class="nhsuk-header__navigation-link" asp-controller="Home" asp-action="Logout">Log out</a>
                        </div>
                    </div>
                }
               @*  <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Command" asp-action="Index">Migration</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Moodle_Migration_WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>